name: CI

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Build
      run: |
          sudo apt-get update
          sudo apt-get -y remove libzstd || true
          sudo apt-get -y install uuid-dev libcurl4-openssl-dev libbz2-dev zlib1g-dev libsnappy-dev liblz4-dev libzstd-dev
          make BUILD_TLS=yes -j$(nproc) KEYDB_CFLAGS='-Werror -Wno-error=infinite-recursion' KEYDB_CXXFLAGS='-Werror -Wno-error=infinite-recursion'
    - name: Unit tests
      run: ./runtest --clients 2 --tags -slow --config server-threads 2
